name: Build HaRepacker (Windows x64)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # --- 新增：打印仓库文件树，帮助定位 .csproj 路径 ---
      - name: List repository files
        run: dir /s

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Publish single-file EXE
        run: |
          dotnet publish HaRepacker/Harepacker-resurrected.csproj \
            -c Release -r win-x64 \
            /p:PublishSingleFile=true /p:PublishTrimmed=true \
            -o output

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: HaRepacker-Win64
          path: output
