name: Build HaRepacker (Windows x64)

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore NuGet packages
        run: dotnet restore HaRepacker/HaRepacker.csproj

      - name: Build solution
        run: dotnet build HaRepacker/HaRepacker.csproj --configuration Release

      - name: Upload artifact
        uses: actions/upload-artifact@4
        with:
          name: HaRepacker-x64
          path: HaRepacker/bin/Release/net8.0-windows/**/*.exe
