build-win64.yml
name: Build HaRepacker (Windows x64)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore NuGet packages
        run: dotnet restore HaRepacker/HaRepacker.csproj

      - name: Build solution
        run: dotnet build HaRepacker/HaRepacker.csproj -c Release --no-restore

      - name: Upload compiled EXE
        uses: actions/upload-artifact@v4
        with:
          name: HaRepacker-x64
          path: HaRepacker/bin/Release/net8.0-windows/**/*.exe
Add GitHub Actions build script for Windows
